-- Auto-generated legal catalog seed from Internet Archive (Public Domain / CC).
-- Generated at: 2026-04-19T16:45:32.554Z
-- Records: 60

with raw_seed_data (
  slug,
  title,
  description,
  release_year,
  runtime_minutes,
  language_code,
  genres,
  countries,
  poster_url,
  backdrop_url,
  source_type,
  license_type,
  license_url,
  attribution_text,
  external_url,
  metadata_json,
  provider_name,
  provider_type,
  source_license_type,
  source_license_url,
  source_attribution_text,
  source_external_url,
  stream_url,
  stream_format,
  quality_label
) as (
  values
(
  'about-bananas-1935-aboutban1935',
  'About Bananas',
  'Complete presentation of the banana industry from the clearing of the jungle and the planting to the shipment of the fruit to the American markets.',
  1935,
  null,
  null,
  '{Agriculture: Bananas,Central America}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/AboutBan1935',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/AboutBan1935',
  '{"identifier":"AboutBan1935","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/AboutBan1935',
  'https://archive.org/download/AboutBan1935/AboutBan1935_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'doctor-in-industry-part-i-1946-doctorin1946',
  'Doctor in Industry (Part I)',
  'Epic history of industrial medicine in the first half of the 20th century, showing how manufacturers and the medical profession came to terms with one another and culminating in GM''s rehabilitation program for returned World War II veterans. Directed by Haford Kerbawy.',
  1946,
  null,
  null,
  '{Medicine: Industrial medicine,Medicine: Occupational health,World War II: Postwar issues}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/Doctorin1946',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/Doctorin1946',
  '{"identifier":"Doctorin1946","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/Doctorin1946',
  'https://archive.org/download/Doctorin1946/Doctorin1946_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'health-your-posture-1953-healthyo1953',
  'Health: Your Posture',
  'Young girl''s mirror image teaches her fundamentals of good posture.',
  1953,
  null,
  null,
  '{Health and hygiene}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/HealthYo1953',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/HealthYo1953',
  '{"identifier":"HealthYo1953","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/HealthYo1953',
  'https://archive.org/download/HealthYo1953/HealthYo1953_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'from-the-ground-up-1954-fromtheg1954',
  'From the Ground Up',
  'Promotional film for "Nutrilite," a 1950s-vintage food supplement.',
  1954,
  null,
  null,
  '{Agriculture: Food industry: Supplements,Nutrition}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/FromtheG1954',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/FromtheG1954',
  '{"identifier":"FromtheG1954","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/FromtheG1954',
  'https://archive.org/download/FromtheG1954/FromtheG1954_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'publicvideos-november-2009-batch-part-4-2009-ace-200911-04',
  'Publicvideos November 2009 batch, part 4',
  'A batch of stock clips made for publicvideos.org.',
  2009,
  null,
  null,
  '{Publicvideos.org,Royalty free,Free,Cc0}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/ace_200911_04',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/publicdomain/zero/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/ace_200911_04',
  '{"identifier":"ace_200911_04","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/publicdomain/zero/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/ace_200911_04',
  'https://archive.org/download/ace_200911_04/00130d67f8ea0c43de91d30cdc13386c.mts-mp430-272.MP4',
  'mp4',
  'h.264 MPEG4'
),
(
  'publicvideos-july-2009-batch-disc-06-2009-ace-200907-06',
  'Publicvideos July 2009 batch, disc 06',
  'A batch of stock clips made for publicvideos.org.',
  2009,
  null,
  null,
  '{Publicvideos.org,Royalty free,Free,Cc0}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/ace_200907_06',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/publicdomain/zero/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/ace_200907_06',
  '{"identifier":"ace_200907_06","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/publicdomain/zero/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/ace_200907_06',
  'https://archive.org/download/ace_200907_06/012daf06069bb4c0b8171a68d176d258.mts-mp430-272.MP4',
  'mp4',
  'h.264 MPEG4'
),
(
  'publicvideos-february-2010-marcio-batch-part-3-2009-taboca-201002-03',
  'Publicvideos February 2010 (Marcio) batch, part 3',
  'A batch of stock clips made for publicvideos.org.',
  2009,
  null,
  null,
  '{Publicvideos.org,Royalty free,Free,Cc0}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/taboca_201002_03',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/publicdomain/zero/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/taboca_201002_03',
  '{"identifier":"taboca_201002_03","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/publicdomain/zero/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/taboca_201002_03',
  'https://archive.org/download/taboca_201002_03/0c53341f060875c7d387c62203170d51.mts-dirac24-272.mp4',
  'mp4',
  'h.264'
),
(
  'beat-sync-capcut-template-2023-download-8-20231018',
  'beat sync capcut template',
  'You can Use this trending template from capcuttemplate.co.in',
  2023,
  null,
  'eng',
  '{Capcuttemplate}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/download-8_20231018',
  null,
  'public_domain',
  'Public Domain',
  'https://creativecommons.org/publicdomain/mark/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/download-8_20231018',
  '{"identifier":"download-8_20231018","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'https://creativecommons.org/publicdomain/mark/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/download-8_20231018',
  'https://archive.org/download/download-8_20231018/download%20(14).mp4',
  'mp4',
  'MPEG4'
),
(
  'publicvideos-november-2009-batch-part-1-2009-ace-200911-03',
  'Publicvideos November 2009 batch, part 1',
  'A batch of stock clips made for publicvideos.org.',
  2009,
  null,
  null,
  '{Publicvideos.org,Royalty free,Free,Cc0}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/ace_200911_03',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/publicdomain/zero/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/ace_200911_03',
  '{"identifier":"ace_200911_03","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/publicdomain/zero/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/ace_200911_03',
  'https://archive.org/download/ace_200911_03/07a3c47a49821d54761a61d704ae0769.mts-mp430-272.MP4',
  'mp4',
  'h.264 MPEG4'
),
(
  'sleep-for-health-1950-sleepfor1950',
  'Sleep for Health',
  'Told from the viewpoint of a child, this film emphasizes that children should train themselves in good sleeping habits. In typical "Goofus and Gallant" style, it shows the advantages a well-rested kid has over his poor-sleeping classmate. Dreams are presented as a normal part of sleeping, and there is a funny dream sequence.',
  1950,
  null,
  null,
  '{Health and hygiene,Dreams,Sleep}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/Sleepfor1950',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/Sleepfor1950',
  '{"identifier":"Sleepfor1950","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/Sleepfor1950',
  'https://archive.org/download/Sleepfor1950/Sleepfor1950_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'joan-avoids-a-cold-1947-joanavoi1947',
  'Joan Avoids a Cold',
  'How young children must behave to avoid transmitting germs to one another.',
  1947,
  null,
  null,
  '{Health and hygiene}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/JoanAvoi1947',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/JoanAvoi1947',
  '{"identifier":"JoanAvoi1947","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/JoanAvoi1947',
  'https://archive.org/download/JoanAvoi1947/JoanAvoi1947_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'capcut-template-download-2024-capcut-template-download',
  'capcut template download',
  'capcut template download',
  2024,
  null,
  'eng',
  '{Capcut template download}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/capcut-template-download',
  null,
  'public_domain',
  'Public Domain',
  'https://creativecommons.org/publicdomain/mark/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/capcut-template-download',
  '{"identifier":"capcut-template-download","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'https://creativecommons.org/publicdomain/mark/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/capcut-template-download',
  'https://archive.org/download/capcut-template-download/1.-6988481571284356354-9879905.mp4',
  'mp4',
  'MPEG4'
),
(
  'eat-for-health-1954-eatforhe1954',
  'Eat for Health',
  'Ralph learns the five food groups, helping him to eat a balanced diet, and has more fun because of his better health.',
  1954,
  null,
  null,
  '{Health and hygiene,Food,Nutrition}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/EatforHe1954',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/EatforHe1954',
  '{"identifier":"EatforHe1954","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/EatforHe1954',
  'https://archive.org/download/EatforHe1954/EatforHe1954_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'big-buck-bunny-bigbuckbunny-124',
  'Big Buck Bunny',
  'Big Buck Bunny is a comedy about a well-tempered rabbit "Big Buck", who finds his day spoiled by the rude actions of the forest bullies, three rodents. In the typical 1950ies cartoon tradition Big Buck then prepares for the rodents a comical revenge. The creative team for the movie were brought together by the Blender Institute from all over the world, including the USA, Denmark, Italy, Germany, t',
  null,
  null,
  null,
  '{Big Buck,Blender}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/BigBuckBunny_124',
  null,
  'cc',
  'CC BY 3.0',
  'http://creativecommons.org/licenses/by/3.0/',
  'Source: Internet Archive',
  'https://archive.org/details/BigBuckBunny_124',
  '{"identifier":"BigBuckBunny_124","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY 3.0',
  'http://creativecommons.org/licenses/by/3.0/',
  'Source: Internet Archive',
  'https://archive.org/details/BigBuckBunny_124',
  'https://archive.org/download/BigBuckBunny_124/Content%2Fbig_buck_bunny_720p_surround.mp4',
  'mp4',
  'h.264'
),
(
  'sex-madness-1938-sex-madness',
  'Sex Madness',
  'This is a typical sex exploitation film from the early 1930s - complete with wild parties, sex out of wedlock, lesbianism, etc. A chorus girl''s exposure to the "casting couch" also exposes her to syphilis. Exploitation filmmakers hoped to capitalize on the taboo subjects of venereal disease, sex before marriage, lesbianism, etc. while skirting the Motion Picture Production Code of 1930 which forba',
  1938,
  null,
  null,
  '{Exploitation,Melodrama}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/sex_madness',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/sex_madness',
  '{"identifier":"sex_madness","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/sex_madness',
  'https://archive.org/download/sex_madness/sex_madness_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'babies-and-breadwinners-part-ii-babies-and-breadwinners-2',
  'Babies and Breadwinners (Part II)',
  'Presented by: U.S. Department of Health, Education and Welfare, Public Health Service and Bureau State Services. Produced by the Communicable Disease Center in cooperation with the Georgia Department of Public Health and the Muscogee Health Department. 0647 PA8739 Babies and Breadwinners',
  null,
  null,
  null,
  '{Motion Pictures: Government,Health and Hygiene,Medicine: Infectious Diseases}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/babies_and_breadwinners_2',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/babies_and_breadwinners_2',
  '{"identifier":"babies_and_breadwinners_2","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/babies_and_breadwinners_2',
  'https://archive.org/download/babies_and_breadwinners_2/babies_and_breadwinners_2_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'elephants-dream-2006-elephantsdream',
  'Elephants Dream',
  'From <a href="http://elephantsdream.org/" rel="ugc nofollow">the official website</a>: "Elephants Dream is the story of two strange characters exploring a capricious and seemingly infinite machine. The elder, Proog, acts as a tour-guide and protector, happily showing off the sights and dangers of the machine to his initially curious but increasingly skeptical protege Emo. As their journey unfolds ',
  2006,
  null,
  'eng',
  '{Open,Movie,Surreal,Animation}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/ElephantsDream',
  null,
  'cc',
  'CC BY 3.0',
  'http://creativecommons.org/licenses/by/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/ElephantsDream',
  '{"identifier":"ElephantsDream","rights":"© Copyright 2006, Blender Foundation / Netherlands Media Art Institute / <a href=\"http://www.elephantsdream.org/\" rel=\"ugc nofollow\">www.elephantsdream.org</a> The movie “Elephants Dream” and all data on the DVDs and almost all of the contents on this website is licensed under the Creative Commons A","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY 3.0',
  'http://creativecommons.org/licenses/by/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/ElephantsDream',
  'https://archive.org/download/ElephantsDream/ed_1024_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'electricsheep-flock-244-32500-3-electricsheep-flock-244-32500-3',
  'electricsheep-flock-244-32500-3',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-32500-3',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-32500-3',
  '{"identifier":"electricsheep-flock-244-32500-3","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-32500-3',
  'https://archive.org/download/electricsheep-flock-244-32500-3/00244%3D32593%3D23650%3D23640_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'right-to-health-a-part-i-right-to-health-1',
  'Right to Health, A (Part I)',
  'A Right to Health, Neighborhood Health Centers in Profile. A Production of Professional Arts, Inc. in San Mateo, CA for the Office of Health Affairs and Office of Economic Opportunity. Directed and Produced by David W. Parker, PhD, Written by Parker and William J. Bicknell, M.D., shot and edited by Peter P. Drowne, narrated by Earle Marsh, M.D. 0726 PA8850 Right to Health, A',
  null,
  null,
  null,
  '{Motion Pictures: Sponsored,Health and Hygiene,Medicine: Public Health}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/right_to_health_1',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/right_to_health_1',
  '{"identifier":"right_to_health_1","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/right_to_health_1',
  'https://archive.org/download/right_to_health_1/right_to_health_1_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'hindi-song-capcut-template-1-2023-hindi-song-capcut-template-1',
  'hindi-song-capcut-template-1',
  '<a href="https://capcuttemplate.co.in/" rel="ugc nofollow">Use template on capcut </a>',
  2023,
  null,
  'eng',
  '{Capcut template}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/hindi-song-capcut-template-1',
  null,
  'public_domain',
  'Public Domain',
  'https://creativecommons.org/publicdomain/mark/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/hindi-song-capcut-template-1',
  '{"identifier":"hindi-song-capcut-template-1","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'https://creativecommons.org/publicdomain/mark/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/hindi-song-capcut-template-1',
  'https://archive.org/download/hindi-song-capcut-template-1/Video-854.mp4',
  'mp4',
  'MPEG4'
),
(
  'electricsheep-flock-244-32500-2-electricsheep-flock-244-32500-2',
  'electricsheep-flock-244-32500-2',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-32500-2',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-32500-2',
  '{"identifier":"electricsheep-flock-244-32500-2","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-32500-2',
  'https://archive.org/download/electricsheep-flock-244-32500-2/00244%3D32592%3D22973%3D22551_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'automotive-service-1940-automoti1940',
  'Automotive Service',
  'Opportunities for employment servicing America''s vast motor fleet.',
  1940,
  null,
  null,
  '{Occupations: Automotive,Car culture: General,Automobiles: Service and repair}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/Automoti1940',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/Automoti1940',
  '{"identifier":"Automoti1940","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/Automoti1940',
  'https://archive.org/download/Automoti1940/Automoti1940_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'videoplay-tv2-pag-1-videoplay-tv2-pag-1',
  'Videoplay Tv2 Pag 1',
  '<div style="color:rgb(44,44,44);font-family:''Helvetica Neue'', Helvetica, Arial, sans-serif;font-size:14px;font-style:normal;font-weight:400;letter-spacing:normal;text-indent:0px;text-transform:none;word-spacing:0px;white-space:normal;background-color:rgb(255,255,255);"><b style="font-weight:bold;">من بریل لایل اریکا هرتزوگ از شهر نیویورک هستم. شبکه من دو بمب لوله‌ای را در سفارت ایران در کوالالامپو',
  null,
  null,
  null,
  '{Videoplay Tv2 Pag 1}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/videoplay-tv2-pag-1',
  null,
  'public_domain',
  'Public Domain',
  'https://creativecommons.org/publicdomain/mark/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/videoplay-tv2-pag-1',
  '{"identifier":"videoplay-tv2-pag-1","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'https://creativecommons.org/publicdomain/mark/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/videoplay-tv2-pag-1',
  'https://archive.org/download/videoplay-tv2-pag-1/7%20seeds.mp4',
  'mp4',
  'h.264'
),
(
  'care-of-the-skin-1949-careofth1949',
  'Care of the Skin',
  'Structure of the skin; good cleanliness habits; the proper way to wash; the correct use of soap.',
  1949,
  null,
  null,
  '{Health and hygiene,Medicine: Dermatology}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/Careofth1949',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/Careofth1949',
  '{"identifier":"Careofth1949","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/Careofth1949',
  'https://archive.org/download/Careofth1949/Careofth1949_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'electricsheep-flock-244-32500-1-electricsheep-flock-244-32500-1',
  'electricsheep-flock-244-32500-1',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-32500-1',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-32500-1',
  '{"identifier":"electricsheep-flock-244-32500-1","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-32500-1',
  'https://archive.org/download/electricsheep-flock-244-32500-1/00244%3D32591%3D22942%3D22973_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'electricsheep-flock-244-80000-7-electricsheep-flock-244-80000-7',
  'electricsheep-flock-244-80000-7',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-80000-7',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-80000-7',
  '{"identifier":"electricsheep-flock-244-80000-7","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-80000-7',
  'https://archive.org/download/electricsheep-flock-244-80000-7/00244%3D80107%3D77393%3D77409.mp4',
  'mp4',
  'h.264'
),
(
  'electricsheep-flock-244-80000-6-electricsheep-flock-244-80000-6',
  'electricsheep-flock-244-80000-6',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-80000-6',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-80000-6',
  '{"identifier":"electricsheep-flock-244-80000-6","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-80000-6',
  'https://archive.org/download/electricsheep-flock-244-80000-6/00244%3D80086%3D79910%3D77346.mp4',
  'mp4',
  'h.264'
),
(
  'electricsheep-flock-244-32500-8-electricsheep-flock-244-32500-8',
  'electricsheep-flock-244-32500-8',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-32500-8',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-32500-8',
  '{"identifier":"electricsheep-flock-244-32500-8","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-32500-8',
  'https://archive.org/download/electricsheep-flock-244-32500-8/00244%3D32508%3D22537%3D22942_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'electricsheep-flock-244-80000-1-electricsheep-flock-244-80000-1',
  'electricsheep-flock-244-80000-1',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-80000-1',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-80000-1',
  '{"identifier":"electricsheep-flock-244-80000-1","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-80000-1',
  'https://archive.org/download/electricsheep-flock-244-80000-1/00244%3D80011%3D77266%3D77346.mp4',
  'mp4',
  'h.264'
),
(
  'electricsheep-flock-244-32500-9-electricsheep-flock-244-32500-9',
  'electricsheep-flock-244-32500-9',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-32500-9',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-32500-9',
  '{"identifier":"electricsheep-flock-244-32500-9","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-32500-9',
  'https://archive.org/download/electricsheep-flock-244-32500-9/00244%3D32649%3D22645%3D23652_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'sniffles-and-sneezes-1955-sniffles1955',
  'Sniffles and Sneezes',
  'Children as carriers and victims of infections.',
  1955,
  null,
  null,
  '{Health and hygiene}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/Sniffles1955',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/Sniffles1955',
  '{"identifier":"Sniffles1955","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/Sniffles1955',
  'https://archive.org/download/Sniffles1955/Sniffles1955_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'electricsheep-flock-244-32500-0-electricsheep-flock-244-32500-0',
  'electricsheep-flock-244-32500-0',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-32500-0',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-32500-0',
  '{"identifier":"electricsheep-flock-244-32500-0","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-32500-0',
  'https://archive.org/download/electricsheep-flock-244-32500-0/00244%3D32650%3D23652%3D23646_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'electricsheep-flock-244-32500-7-electricsheep-flock-244-32500-7',
  'electricsheep-flock-244-32500-7',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-32500-7',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-32500-7',
  '{"identifier":"electricsheep-flock-244-32500-7","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-32500-7',
  'https://archive.org/download/electricsheep-flock-244-32500-7/00244%3D32507%3D23651%3D22645_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'electricsheep-flock-244-80000-8-electricsheep-flock-244-80000-8',
  'electricsheep-flock-244-80000-8',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-80000-8',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-80000-8',
  '{"identifier":"electricsheep-flock-244-80000-8","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-80000-8',
  'https://archive.org/download/electricsheep-flock-244-80000-8/00244%3D80068%3D79894%3D79910.mp4',
  'mp4',
  'h.264'
),
(
  'park-conscious-1938-parkcons1938',
  'Park Conscious',
  'Elegy to recreation and relaxation in state and national parks.',
  1938,
  null,
  null,
  '{Recreation,Parks,Nature}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/ParkCons1938',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/ParkCons1938',
  '{"identifier":"ParkCons1938","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/ParkCons1938',
  'https://archive.org/download/ParkCons1938/ParkCons1938_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'electricsheep-flock-244-80000-4-electricsheep-flock-244-80000-4',
  'electricsheep-flock-244-80000-4',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-80000-4',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-80000-4',
  '{"identifier":"electricsheep-flock-244-80000-4","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-80000-4',
  'https://archive.org/download/electricsheep-flock-244-80000-4/00244%3D80014%3D79894%3D79895.mp4',
  'mp4',
  'h.264'
),
(
  'electricsheep-flock-244-82500-7-electricsheep-flock-244-82500-7',
  'electricsheep-flock-244-82500-7',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-82500-7',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-82500-7',
  '{"identifier":"electricsheep-flock-244-82500-7","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-82500-7',
  'https://archive.org/download/electricsheep-flock-244-82500-7/00244%3D82547%3D82021%3D82019.mp4',
  'mp4',
  'h.264'
),
(
  'electricsheep-flock-244-32500-4-electricsheep-flock-244-32500-4',
  'electricsheep-flock-244-32500-4',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-32500-4',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-32500-4',
  '{"identifier":"electricsheep-flock-244-32500-4","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-32500-4',
  'https://archive.org/download/electricsheep-flock-244-32500-4/00244%3D32654%3D23015%3D22942_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'electricsheep-flock-244-80000-9-electricsheep-flock-244-80000-9',
  'electricsheep-flock-244-80000-9',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-80000-9',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-80000-9',
  '{"identifier":"electricsheep-flock-244-80000-9","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-80000-9',
  'https://archive.org/download/electricsheep-flock-244-80000-9/00244%3D80009%3D79407%3D79896.mp4',
  'mp4',
  'h.264'
),
(
  'electricsheep-flock-244-32500-6-electricsheep-flock-244-32500-6',
  'electricsheep-flock-244-32500-6',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-32500-6',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-32500-6',
  '{"identifier":"electricsheep-flock-244-32500-6","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-32500-6',
  'https://archive.org/download/electricsheep-flock-244-32500-6/00244%3D32506%3D22645%3D23651_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'electricsheep-flock-244-80000-3-electricsheep-flock-244-80000-3',
  'electricsheep-flock-244-80000-3',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-80000-3',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-80000-3',
  '{"identifier":"electricsheep-flock-244-80000-3","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-80000-3',
  'https://archive.org/download/electricsheep-flock-244-80000-3/00244%3D80013%3D77374%3D79895.mp4',
  'mp4',
  'h.264'
),
(
  'electricsheep-flock-244-72500-8-electricsheep-flock-244-72500-8',
  'electricsheep-flock-244-72500-8',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-72500-8',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-72500-8',
  '{"identifier":"electricsheep-flock-244-72500-8","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-72500-8',
  'https://archive.org/download/electricsheep-flock-244-72500-8/00244%3D72528%3D72528%3D72528.mp4',
  'mp4',
  'h.264'
),
(
  'electricsheep-flock-244-80000-2-electricsheep-flock-244-80000-2',
  'electricsheep-flock-244-80000-2',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-80000-2',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-80000-2',
  '{"identifier":"electricsheep-flock-244-80000-2","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-80000-2',
  'https://archive.org/download/electricsheep-flock-244-80000-2/00244%3D80012%3D77323%3D77374.mp4',
  'mp4',
  'h.264'
),
(
  'electricsheep-flock-244-75000-3-electricsheep-flock-244-75000-3',
  'electricsheep-flock-244-75000-3',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-75000-3',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-75000-3',
  '{"identifier":"electricsheep-flock-244-75000-3","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-75000-3',
  'https://archive.org/download/electricsheep-flock-244-75000-3/00244%3D75033%3D74520%3D74624.mp4',
  'mp4',
  'h.264'
),
(
  'electricsheep-flock-244-32500-5-electricsheep-flock-244-32500-5',
  'electricsheep-flock-244-32500-5',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-32500-5',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-32500-5',
  '{"identifier":"electricsheep-flock-244-32500-5","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-32500-5',
  'https://archive.org/download/electricsheep-flock-244-32500-5/00244%3D32655%3D22706%3D23649_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'electricsheep-flock-244-82500-8-electricsheep-flock-244-82500-8',
  'electricsheep-flock-244-82500-8',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-82500-8',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-82500-8',
  '{"identifier":"electricsheep-flock-244-82500-8","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-82500-8',
  'https://archive.org/download/electricsheep-flock-244-82500-8/00244%3D82548%3D82016%3D82545.mp4',
  'mp4',
  'h.264'
),
(
  'personal-hygiene-part-i-1950-personal1950',
  'Personal Hygiene (Part I)',
  'Military training drama showing how the residents of a barracks convince a sloppy soldier to clean up his act. With many folk songs on cleanliness.',
  1950,
  null,
  null,
  '{Health and hygiene,Military,Music: Folk}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/Personal1950',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/Personal1950',
  '{"identifier":"Personal1950","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/Personal1950',
  'https://archive.org/download/Personal1950/Personal1950_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'electricsheep-flock-244-82500-5-electricsheep-flock-244-82500-5',
  'electricsheep-flock-244-82500-5',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-82500-5',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-82500-5',
  '{"identifier":"electricsheep-flock-244-82500-5","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-82500-5',
  'https://archive.org/download/electricsheep-flock-244-82500-5/00244%3D82515%3D82015%3D82514.mp4',
  'mp4',
  'h.264'
),
(
  'electricsheep-flock-244-82500-6-electricsheep-flock-244-82500-6',
  'electricsheep-flock-244-82500-6',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-82500-6',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-82500-6',
  '{"identifier":"electricsheep-flock-244-82500-6","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-82500-6',
  'https://archive.org/download/electricsheep-flock-244-82500-6/00244%3D82516%3D82514%3D82444.mp4',
  'mp4',
  'h.264'
),
(
  'electricsheep-flock-244-80000-5-electricsheep-flock-244-80000-5',
  'electricsheep-flock-244-80000-5',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-80000-5',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-80000-5',
  '{"identifier":"electricsheep-flock-244-80000-5","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-80000-5',
  'https://archive.org/download/electricsheep-flock-244-80000-5/00244%3D80025%3D77392%3D77323.mp4',
  'mp4',
  'h.264'
),
(
  'electricsheep-flock-244-82500-2-electricsheep-flock-244-82500-2',
  'electricsheep-flock-244-82500-2',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-82500-2',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-82500-2',
  '{"identifier":"electricsheep-flock-244-82500-2","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-82500-2',
  'https://archive.org/download/electricsheep-flock-244-82500-2/00244%3D82512%3D82017%3D82509.mp4',
  'mp4',
  'h.264'
),
(
  'electricsheep-flock-244-20000-8-electricsheep-flock-244-20000-8',
  'electricsheep-flock-244-20000-8',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-20000-8',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-20000-8',
  '{"identifier":"electricsheep-flock-244-20000-8","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-20000-8',
  'https://archive.org/download/electricsheep-flock-244-20000-8/00244%3D20028%3D20026%3D09995_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'electricsheep-flock-244-72500-9-electricsheep-flock-244-72500-9',
  'electricsheep-flock-244-72500-9',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-72500-9',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-72500-9',
  '{"identifier":"electricsheep-flock-244-72500-9","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-72500-9',
  'https://archive.org/download/electricsheep-flock-244-72500-9/00244%3D72509%3D72509%3D72509.mp4',
  'mp4',
  'h.264'
),
(
  'electricsheep-flock-244-20000-0-electricsheep-flock-244-20000-0',
  'electricsheep-flock-244-20000-0',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-20000-0',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-20000-0',
  '{"identifier":"electricsheep-flock-244-20000-0","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-20000-0',
  'https://archive.org/download/electricsheep-flock-244-20000-0/00244%3D20560%3D10992%3D10947_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'electricsheep-flock-244-20000-6-electricsheep-flock-244-20000-6',
  'electricsheep-flock-244-20000-6',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-20000-6',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-20000-6',
  '{"identifier":"electricsheep-flock-244-20000-6","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-20000-6',
  'https://archive.org/download/electricsheep-flock-244-20000-6/00244%3D20566%3D08117%3D12093_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'electricsheep-flock-244-72500-0-electricsheep-flock-244-72500-0',
  'electricsheep-flock-244-72500-0',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-72500-0',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-72500-0',
  '{"identifier":"electricsheep-flock-244-72500-0","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-72500-0',
  'https://archive.org/download/electricsheep-flock-244-72500-0/00244%3D72520%3D72520%3D72520.mp4',
  'mp4',
  'h.264'
),
(
  'electricsheep-flock-244-20000-9-electricsheep-flock-244-20000-9',
  'electricsheep-flock-244-20000-9',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-20000-9',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-20000-9',
  '{"identifier":"electricsheep-flock-244-20000-9","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-20000-9',
  'https://archive.org/download/electricsheep-flock-244-20000-9/00244%3D20389%3D20389%3D20389_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'electricsheep-flock-244-82500-1-electricsheep-flock-244-82500-1',
  'electricsheep-flock-244-82500-1',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-82500-1',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-82500-1',
  '{"identifier":"electricsheep-flock-244-82500-1","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-82500-1',
  'https://archive.org/download/electricsheep-flock-244-82500-1/00244%3D82511%3D82018%3D82012.mp4',
  'mp4',
  'h.264'
),
(
  'fred-and-the-voice-of-food-safety-how-to-avoid-food-borne-illness-govntisava18185vnb1',
  'Fred and the Voice of Food Safety: How to Avoid Food-Borne Illness',
  'Food and Drug Administration<br /><br />gov.ntis.ava18185vnb1<br /><br />Fred and the Voice of Food Safety: How to Avoid Food-Borne Illness<br /><br />About 2 million cases of food poisoning which now occur each year are due to improper handling of food in the home. This presentation teaches how to handle, thaw, and store food properly to avoid foodborne illness. Fred''s wife has returned to the wo',
  null,
  null,
  'eng',
  '{Fda.gov,Public.resource.org}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/gov.ntis.ava18185vnb1',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/zero/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/gov.ntis.ava18185vnb1',
  '{"identifier":"gov.ntis.ava18185vnb1","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/zero/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/gov.ntis.ava18185vnb1',
  'https://archive.org/download/gov.ntis.ava18185vnb1/gov.ntis.ava18185vnb1_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'electricsheep-flock-244-20000-7-electricsheep-flock-244-20000-7',
  'electricsheep-flock-244-20000-7',
  'Archive of flock 244 of the Electric Sheep, see http://electricsheep.org and http://scottdraves.com',
  null,
  null,
  null,
  '{Electricsheep,Alife,Art,Draves}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/electricsheep-flock-244-20000-7',
  null,
  'cc',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-20000-7',
  '{"identifier":"electricsheep-flock-244-20000-7","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'CC BY-NC 3.0',
  'http://creativecommons.org/licenses/by-nc/3.0/us/',
  'Source: Internet Archive',
  'https://archive.org/details/electricsheep-flock-244-20000-7',
  'https://archive.org/download/electricsheep-flock-244-20000-7/00244%3D20027%3D10348%3D20026_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
)
),
seed_data as (
  select
    slug::text as slug,
    title::text as title,
    description::text as description,
    release_year::integer as release_year,
    runtime_minutes::integer as runtime_minutes,
    language_code::text as language_code,
    genres::text[] as genres,
    countries::text[] as countries,
    poster_url::text as poster_url,
    backdrop_url::text as backdrop_url,
    source_type::text as source_type,
    license_type::text as license_type,
    license_url::text as license_url,
    attribution_text::text as attribution_text,
    external_url::text as external_url,
    metadata_json::jsonb as metadata_json,
    provider_name::text as provider_name,
    provider_type::text as provider_type,
    source_license_type::text as source_license_type,
    source_license_url::text as source_license_url,
    source_attribution_text::text as source_attribution_text,
    source_external_url::text as source_external_url,
    stream_url::text as stream_url,
    stream_format::text as stream_format,
    quality_label::text as quality_label
  from raw_seed_data
),
upsert_items as (
  insert into public.legal_catalog_items (
    slug,
    title,
    description,
    release_year,
    runtime_minutes,
    language_code,
    genres,
    countries,
    poster_url,
    backdrop_url,
    source_type,
    license_type,
    license_url,
    attribution_text,
    external_url,
    metadata_json,
    is_active
  )
  select
    slug,
    title,
    description,
    release_year,
    runtime_minutes,
    language_code,
    genres,
    countries,
    poster_url,
    backdrop_url,
    source_type,
    license_type,
    license_url,
    attribution_text,
    external_url,
    metadata_json,
    true
  from seed_data
  on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    release_year = excluded.release_year,
    runtime_minutes = excluded.runtime_minutes,
    language_code = excluded.language_code,
    genres = excluded.genres,
    countries = excluded.countries,
    poster_url = excluded.poster_url,
    source_type = excluded.source_type,
    license_type = excluded.license_type,
    license_url = excluded.license_url,
    attribution_text = excluded.attribution_text,
    external_url = excluded.external_url,
    metadata_json = excluded.metadata_json,
    is_active = true,
    updated_at = now()
  returning id, slug
),
insert_sources as (
  insert into public.legal_sources (
    item_id,
    provider_name,
    provider_type,
    license_type,
    license_url,
    attribution_text,
    territories,
    external_watch_url,
    metadata_json,
    is_active
  )
  select
    i.id,
    s.provider_name,
    s.provider_type,
    s.source_license_type,
    s.source_license_url,
    s.source_attribution_text,
    '{}'::text[],
    s.source_external_url,
    jsonb_build_object('seed', 'archive_org'),
    true
  from seed_data s
  join public.legal_catalog_items i on i.slug = s.slug
  where not exists (
    select 1
    from public.legal_sources ls
    where ls.item_id = i.id
      and ls.provider_name = s.provider_name
      and ls.external_watch_url = s.source_external_url
  )
  returning id, item_id
)
insert into public.legal_stream_variants (
  item_id,
  source_id,
  stream_url,
  format,
  quality_label,
  region_allowlist,
  requires_auth,
  is_embeddable,
  is_active,
  metadata_json
)
select
  i.id,
  src.id,
  s.stream_url,
  s.stream_format,
  s.quality_label,
  '{}'::text[],
  false,
  true,
  true,
  jsonb_build_object('seed', 'archive_org')
from seed_data s
join public.legal_catalog_items i on i.slug = s.slug
left join lateral (
  select ls.id
  from public.legal_sources ls
  where ls.item_id = i.id
  order by ls.id desc
  limit 1
) src on true
where s.stream_url is not null
  and s.stream_url <> ''
  and not exists (
    select 1
    from public.legal_stream_variants lv
    where lv.item_id = i.id
      and lv.stream_url = s.stream_url
  );
