-- Auto-generated legal catalog seed from Internet Archive (Public Domain / CC).
-- Generated at: 2026-04-19T17:33:02.345Z
-- Records: 55

-- Cleanup previous auto-seeded Internet Archive rows.
delete from public.legal_stream_variants
where item_id in (
  select id
  from public.legal_catalog_items
  where metadata_json->>'provider' = 'internet_archive'
);

delete from public.legal_sources
where item_id in (
  select id
  from public.legal_catalog_items
  where metadata_json->>'provider' = 'internet_archive'
);

delete from public.legal_catalog_items
where metadata_json->>'provider' = 'internet_archive';

create temporary table tmp_legal_seed (
  slug text not null,
  title text not null,
  description text,
  release_year integer,
  runtime_minutes integer,
  language_code text,
  genres text[] not null default '{}',
  countries text[] not null default '{}',
  poster_url text,
  backdrop_url text,
  source_type text not null,
  license_type text not null,
  license_url text not null,
  attribution_text text,
  external_url text,
  metadata_json jsonb not null default '{}'::jsonb,
  provider_name text not null,
  provider_type text not null,
  source_license_type text not null,
  source_license_url text not null,
  source_attribution_text text,
  source_external_url text,
  stream_url text,
  stream_format text,
  quality_label text
) on commit drop;

insert into tmp_legal_seed (
  slug,
  title,
  description,
  release_year,
  runtime_minutes,
  language_code,
  genres,
  countries,
  poster_url,
  backdrop_url,
  source_type,
  license_type,
  license_url,
  attribution_text,
  external_url,
  metadata_json,
  provider_name,
  provider_type,
  source_license_type,
  source_license_url,
  source_attribution_text,
  source_external_url,
  stream_url,
  stream_format,
  quality_label
)
values
(
  'sex-madness-1938-sex-madness',
  'Sex Madness',
  'This is a typical sex exploitation film from the early 1930s - complete with wild parties, sex out of wedlock, lesbianism, etc. A chorus girl''s exposure to the "casting couch" also exposes her to syphilis. Exploitation filmmakers hoped to capitalize on the taboo subjects of venereal disease, sex before marriage, lesbianism, etc. while skirting the Motion Picture Production Code of 1930 which forba',
  1938,
  null,
  null,
  '{Exploitation,Melodrama}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/sex_madness',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/sex_madness',
  '{"identifier":"sex_madness","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/sex_madness',
  'https://archive.org/download/sex_madness/sex_madness_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'charlie-chaplin-festival-1938-charlie-chaplin-film-fest',
  'Charlie Chaplin Festival',
  'Four Chaplin shorts from 1917: The Adventurer, The Cure, Easy Street and The Immigrant, presented with music and sound effects. You can find more information regarding this film on <a href="http://imdb.com/title/tt0284688/" rel="ugc nofollow">its IMDb page</a>.',
  1938,
  77,
  null,
  '{Comedy}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/charlie_chaplin_film_fest',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/charlie_chaplin_film_fest',
  '{"identifier":"charlie_chaplin_film_fest","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/charlie_chaplin_film_fest',
  'https://archive.org/download/charlie_chaplin_film_fest/charlie_chaplin_film_fest_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'voyage-to-the-planet-of-prehistoric-women-1967-voyagetotheplanetofprehistoricwomen',
  'Voyage to the Planet of Prehistoric Women',
  'A team of astronauts crashes on the surface of Venus. Accompanied by their robot, they explore the surface and end up destroying the Venusian God. This film is also known as "The Gill Women" and "The Gill Women of Venus". This film began life as a Soviet-produced work. An American producer then added some new footage and changed the credits to hide the film''s Soviet origin. The original film, "Pla',
  1967,
  79,
  'eng',
  '{1960s,Soviet,Space,Pdmovies}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/VoyagetothePlanetofPrehistoricWomen',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/VoyagetothePlanetofPrehistoricWomen',
  '{"identifier":"VoyagetothePlanetofPrehistoricWomen","rights":"Copyright 1967 by The Filmgroup, Inc. (expired)","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/VoyagetothePlanetofPrehistoricWomen',
  'https://archive.org/download/VoyagetothePlanetofPrehistoricWomen/VoyagetothePlanetofPrehistoricWomen_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'house-on-haunted-hill-1959-house-on-haunted-hill-ipod',
  'House on Haunted Hill',
  'Frederick Loren has invited five strangers to a party of a lifetime. He is offering each of them $10,000 if they can stay the night in a house.',
  1959,
  74,
  null,
  '{Drama,Horror,Thriller}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/house_on_haunted_hill_ipod',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/house_on_haunted_hill_ipod',
  '{"identifier":"house_on_haunted_hill_ipod","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/house_on_haunted_hill_ipod',
  'https://archive.org/download/house_on_haunted_hill_ipod/house_on_haunted_hill_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'jungle-book-1942-junglebook',
  'Jungle Book',
  'Teenaged Mowgli, who was raised by wolves, appears in a village in India and is adopted by Messua. Mowgli learns human language and some human ways quickly, though keeping jungle ideas. Influential Merchant Buldeo is bigoted against ''beasts'' including Mowgli; not so Buldeo''s pretty daughter, whom Mowgli takes on a jungle tour where they find a treasure, setting the evil of human greed in motion. N',
  1942,
  108,
  null,
  '{Fantasy,Action,Adventure,Sabu Dastagir}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/JungleBook',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/JungleBook',
  '{"identifier":"JungleBook","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/JungleBook',
  'https://archive.org/download/JungleBook/Jungle_Book_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'reefer-madness-1938-reefer-madness1938',
  'Reefer Madness',
  '<b>Considered THE archetypal sensationalized anti-drug movie, but it''s really an exploitation film made to capitalize on the hot taboo subject of marijuana use.</b> Like many exploitation films of the time, "Reefer Madness" tried to make a quick buck off of a forbidden subject while skirting the Motion Picture Production Code of 1930. The Code forbade the portrayal of immoral acts like drug use. (',
  1938,
  68,
  null,
  '{Exploitation,Cult,Pdmovies}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/reefer_madness1938',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/reefer_madness1938',
  '{"identifier":"reefer_madness1938","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/reefer_madness1938',
  'https://archive.org/download/reefer_madness1938/reefer_madness1938_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'sita-sings-the-blues-2008-sita-sings-the-blues',
  'Sita Sings the Blues',
  'Sita is a goddess separated from her beloved Lord and husband Rama. Nina is an animator whose husband moves to India, then dumps her by email. Three hilarious shadow puppets narrate both ancient tragedy and modern comedy in this beautifully animated interpretation of the Indian epic Ramayana. Set to the 1920''s jazz vocals of Annette Hanshaw, Sita Sings the Blues earns its tagline as "the Greatest ',
  2008,
  81,
  null,
  '{Classic}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/Sita_Sings_the_Blues',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/publicdomain/zero/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/Sita_Sings_the_Blues',
  '{"identifier":"Sita_Sings_the_Blues","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/publicdomain/zero/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/Sita_Sings_the_Blues',
  'https://archive.org/download/Sita_Sings_the_Blues/SITA_SINGS_MOVIE_ONLY.mp4',
  'mp4',
  'h.264'
),
(
  'the-pied-piper-of-hamelin-1957-the-pied-piper-of-hamelin',
  'The Pied Piper of Hamelin',
  'Stars Van Johnson, Claude Rains, Jim Backus Tagline: "Now! a giant color spectacle! from the pages of the immortal classics comes this famous story" Information regarding this film on <a href="http://www.imdb.com/title/tt0050842/" rel="ugc nofollow">its IMDb page</a>. More information on <a href="http://en.wikipedia.org/wiki/Pied_piper" rel="ugc nofollow">Wikipedia </a>.',
  1957,
  89,
  null,
  '{Fantasy,Musical,Fairy tale}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/The_Pied_Piper_of_Hamelin',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/The_Pied_Piper_of_Hamelin',
  '{"identifier":"The_Pied_Piper_of_Hamelin","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/The_Pied_Piper_of_Hamelin',
  'https://archive.org/download/The_Pied_Piper_of_Hamelin/pied.mp4',
  'mp4',
  'h.264'
),
(
  'nazi-concentration-camps-1945-nazi-concentration-camps',
  'Nazi Concentration Camps',
  '**This film contains extremely graphic scenes of human suffering, please exercise caution when viewing.**<br /><br /> Compilation footage of Nazi concentration camps in the immediate aftermath of World War II. The footage was gathered by the US Department of Defense as part of the effort to conduct war crimes trials.<br /><br /> This copy was dubbed from a video copy at the National Archives in Co',
  1945,
  3116,
  null,
  '{Nazi,War,World war II,Concentration camp}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/nazi_concentration_camps',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/nazi_concentration_camps',
  '{"identifier":"nazi_concentration_camps","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/nazi_concentration_camps',
  'https://archive.org/download/nazi_concentration_camps/nazi_concentration_camps_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'bloody-pit-of-horror-1965-bloodypitofhorror',
  'Bloody Pit of Horror',
  'A group of models and cameramen go to a castle to shoot covers for horror novels where they''re captured and tortured by the castle''s owner, the Crimson Executioner. Find out more about this film on <a href="http://www.imdb.com/title/tt0058983/" rel="ugc nofollow">it''s IMDB page</a>.',
  1965,
  82,
  'eng',
  '{Horror}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/BloodyPitOfHorror',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/BloodyPitOfHorror',
  '{"identifier":"BloodyPitOfHorror","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/BloodyPitOfHorror',
  'https://archive.org/download/BloodyPitOfHorror/BloodyPitOfHorror.mp4',
  'mp4',
  'h.264'
),
(
  'abraham-lincoln-1930-abraham-lincoln',
  'Abraham Lincoln',
  'A biography of the beloved United States president by D. W. Griffith. You can find more information regarding this film on <a href="http://www.imdb.com/title/tt0020620/" rel="ugc nofollow">its IMDb page</a>.',
  1930,
  84,
  null,
  '{Pdmovies}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/abraham_lincoln',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/abraham_lincoln',
  '{"identifier":"abraham_lincoln","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/abraham_lincoln',
  'https://archive.org/download/abraham_lincoln/abraham_lincoln_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'dressed-to-kill-1946-dressed-to-kill',
  'Dressed To Kill',
  'Aka ''Sherlock Holmes in Dressed To Kill'' - features Basil Rathbone as Sherlock Holmes. You can find more information regarding this film on <a href="http://www.imdb.com/title/tt0038494/" rel="ugc nofollow">its IMDb page</a>.',
  1946,
  71,
  null,
  '{Mystery,Thriller,Pdmovies}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/dressed_to_kill',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/dressed_to_kill',
  '{"identifier":"dressed_to_kill","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/dressed_to_kill',
  'https://archive.org/download/dressed_to_kill/dressed_to_kill_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'diary-of-a-nudist-1961-diaryofanudist',
  'Diary of a Nudist',
  'The Film follows a reporter (Davee Decker) as she infiltrates a nudist colony in the hopes of exposing its immoral ways. However, once there, she finds herself enjoying it a little bit more than she anticipated. This Film was extremely controversial in 1961 today, films like this are considered to be curiosity pieces.',
  1961,
  72,
  null,
  '{Romance}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/DiaryofaNudist',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/publicdomain/mark/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/DiaryofaNudist',
  '{"identifier":"DiaryofaNudist","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/publicdomain/mark/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/DiaryofaNudist',
  'https://archive.org/download/DiaryofaNudist/DiaryofaNudist_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'suddenly-1954-suddenly',
  'Suddenly',
  '"Three gunmen, who have been hired to assassinate the President, hold a family hostage while waiting for their target. Interesting B film which focuses on psychopathic killer well-portrayed against type by Frank Sinatra." - noir expert Spencer Selby | Cast: Frank Sinatra, Sterling Hayden, James Gleason, Nancy Gates. 77 min.',
  1954,
  75,
  null,
  '{Crime,Drama,Frank Sinatra,Sterling Hayden}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/suddenly',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/suddenly',
  '{"identifier":"suddenly","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/suddenly',
  'https://archive.org/download/suddenly/suddenly_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'the-stranger-1946-thestranger-0',
  'The Stranger',
  'Set Connecticut after World War II, The Stranger is a cat and mouse game between Wilson (Edward G. Robinson), a member of the Allied War Crimes Commission and Franz Kindler (Orson Welles), a Nazi who has assumed the false identity of Dr. Charles Rankin. To complete his new intelligentsia disguise, Kindler marries Mary Longstreet, daughter of a Supreme Court justice.',
  1946,
  95,
  null,
  '{Drama,Film-Noir,Mystery,Thriller}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/TheStranger_0',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/TheStranger_0',
  '{"identifier":"TheStranger_0","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/TheStranger_0',
  'https://archive.org/download/TheStranger_0/The_Stranger_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'tarzans-revenge-1938-tarzans-revenge',
  'Tarzan''s Revenge',
  'You can find more information regarding this film on <a href="http://www.imdb.com/title/tt0030833/" rel="ugc nofollow">its IMDb page</a>.',
  1938,
  null,
  null,
  '{Adventure}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/tarzans_revenge',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/tarzans_revenge',
  '{"identifier":"tarzans_revenge","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/tarzans_revenge',
  'https://archive.org/download/tarzans_revenge/tarzans_revenge_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'mclintock-1963-mclintok-widescreen',
  'McLintock!',
  'John Wayne Comedy Western filmed in widescreeen.',
  1963,
  126,
  null,
  '{John Wayne,Comedy,Western}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/mclintok_widescreen',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/mclintok_widescreen',
  '{"identifier":"mclintok_widescreen","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/mclintok_widescreen',
  'https://archive.org/download/mclintok_widescreen/McLintock_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'my-favorite-brunette-1947-my-favorite-brunette',
  'My Favorite Brunette',
  'Bob Hope comedy with Dorothy Lamour. | You can find more information regarding this film on <a href="http://imdb.com/title/tt0039645/" rel="ugc nofollow">its IMDb page</a>.',
  1947,
  86,
  null,
  '{Comedy,Pdmovies}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/my_favorite_brunette',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/my_favorite_brunette',
  '{"identifier":"my_favorite_brunette","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/my_favorite_brunette',
  'https://archive.org/download/my_favorite_brunette/my_favorite_brunette_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'the-naked-witch-thenakedwitch',
  'The Naked Witch',
  'One of Larry Buchanan''s first films, so don''t expect the polish and complex character interactions of his later work, like "Mars Needs Women" or "Zontar, the Thing from Venus."',
  null,
  3547,
  null,
  '{Horror,Larry Buchanan,Schlock}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/TheNakedWitch',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/publicdomain/mark/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/TheNakedWitch',
  '{"identifier":"TheNakedWitch","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/publicdomain/mark/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/TheNakedWitch',
  'https://archive.org/download/TheNakedWitch/TheNakedWitch1964FullMovieFilmHorror.mp4',
  'mp4',
  'MPEG4'
),
(
  'gullivers-travels-1939-gullivers-travels1939',
  'Gulliver''s Travels',
  'You can find more information regarding this film on <a href="http://www.imdb.com/title/tt0031397/" rel="ugc nofollow">its IMDb page</a>.',
  1939,
  72,
  null,
  '{Animation}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/gullivers_travels1939',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/gullivers_travels1939',
  '{"identifier":"gullivers_travels1939","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/gullivers_travels1939',
  'https://archive.org/download/gullivers_travels1939/gullivers_travels1939_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'the-phantom-of-the-opera-1925-thephantomoftheopera',
  'The Phantom of the Opera',
  'At the Opera of Paris, a mysterious phantom threatens a famous lyric singer, Carlotta and thus forces her to give up her role (Marguerite in Faust) for unknown Christine Daae. Christine meets this phantom (a masked man) in the catacombs, where he lives.',
  1925,
  106,
  null,
  '{Silent,Drama,Horror,Pdmovies}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/ThePhantomoftheOpera',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/ThePhantomoftheOpera',
  '{"identifier":"ThePhantomoftheOpera","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/ThePhantomoftheOpera',
  'https://archive.org/download/ThePhantomoftheOpera/Phantom_of_the_Opera_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  '20000-leagues-under-the-sea-1916-20000leaguesunderthesea',
  '20,000 Leagues Under the Sea',
  'The Universal Film Manufacturing Company was not known in the silent era as premier producer of motion pictures. Yet, in 1916 they produced a film that could not be made effectively without expensive special effects and special photography. The novel had previously been made as short films in 1907 by Georges MÃÂ©liÃÂ¨s and in 1913 by French company ÃÂclair.) Marshalling the expertise underwater ex',
  1916,
  108,
  null,
  '{Silent,Drama}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/20000LeaguesUndertheSea',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/20000LeaguesUndertheSea',
  '{"identifier":"20000LeaguesUndertheSea","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/20000LeaguesUndertheSea',
  'https://archive.org/download/20000LeaguesUndertheSea/20000_Leagues_Under_the_Sea_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'invasion-of-the-bee-girls-invasionofthebeegirls',
  'Invasion of the Bee girls',
  'This one''s about strange women who love their men to death, literally! Maybe the fact that there''s a research facility doing top secret experiments might have something to do with the suspicious deaths.',
  null,
  null,
  null,
  '{Horror,Scifi,Feature films}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/InvasionOfTheBeeGirls',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/InvasionOfTheBeeGirls',
  '{"identifier":"InvasionOfTheBeeGirls","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/InvasionOfTheBeeGirls',
  'https://archive.org/download/InvasionOfTheBeeGirls/InvasionOfTheBeeGirls_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'the-lost-world-1925-lost-world',
  'The Lost World',
  'The first film adaptation of Sir Arthur Conan Doyle''s classic novel about a land where prehistoric creatures still roam.You can find more information regarding this film on <a href="http://www.imdb.com/title/tt0016039/" rel="ugc nofollow">its IMDb page</a>.',
  1925,
  null,
  null,
  '{Adventure,Fantasy}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/lost_world',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/lost_world',
  '{"identifier":"lost_world","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/lost_world',
  'https://archive.org/download/lost_world/lost_world_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'grave-of-the-vampire-1974-grave-of-the-vampire-movie',
  'Grave of the Vampire',
  '<table width="95%" align="center" cellpadding="12"><tr bgcolor="#DDDDDD"><td> <font size="+1">William Smith tracks down his father, a vampire who raped his mother. The IMDB entry is <a href="http://www.imdb.com/title/tt0068658/" rel="ugc nofollow">here</a>. </font> </td> </tr></table> The mpeg2 file has nav-packets, so you can load it into DVDAuthorGUI (a free program) to create a DVD to watch on ',
  1974,
  89,
  null,
  '{Vampire,William Smith,Michael Pataki,Lyn Peters}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/Grave_of_the_Vampire_movie',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/Grave_of_the_Vampire_movie',
  '{"identifier":"Grave_of_the_Vampire_movie","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/Grave_of_the_Vampire_movie',
  'https://archive.org/download/Grave_of_the_Vampire_movie/Grave-of-the-Vampire_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'killers-from-space-1954-killers-from-space',
  'Killers From Space',
  'Attack by monsters from another planet! <a href="http://imdb.com/title/tt0047149/" rel="ugc nofollow">IMDB page</a>',
  1954,
  71,
  null,
  '{Science Fiction}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/Killers_from_space',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/Killers_from_space',
  '{"identifier":"Killers_from_space","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/Killers_from_space',
  'https://archive.org/download/Killers_from_space/Killers_from_space_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'das-kabinett-des-doktor-caligari-the-cabinet-of-dr-caligari-1919-daskabinettdesdoktorcaligarithecabi',
  'Das Kabinett des Doktor Caligari ( The Cabinet of Dr. Caligari )',
  'The Cabinet of Dr. Caligari is the first modern Horror Film and it influence a number of contemporary productions. A real classic! PLOT: A man named Francis relates a story about his best friend Alan and his fiancée Jane. Alan takes him to a fair where they meet Dr. Caligari, who exhibits a somnambulist, Cesare, that can predict the future. When Alan asks how long he has to live, Cesare says he ha',
  1919,
  51,
  null,
  '{Silent,Fantasy,Horror,German Expressionism}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/DasKabinettdesDoktorCaligariTheCabinetofDrCaligari',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/DasKabinettdesDoktorCaligariTheCabinetofDrCaligari',
  '{"identifier":"DasKabinettdesDoktorCaligariTheCabinetofDrCaligari","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/DasKabinettdesDoktorCaligariTheCabinetofDrCaligari',
  'https://archive.org/download/DasKabinettdesDoktorCaligariTheCabinetofDrCaligari/The_Cabinet_of_Dr._Caligari_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'as-you-like-it-1936-asyoulikeit1936',
  'As You Like It',
  'In this first film version of William Shakespeare''s classic pastoral comedy, Sir Laurence Olivier stars as Orlando while Elisabeth Bergner is Rosalind, his secret admirer who disguises herself as a boy in order to stay near to him. Nearly all of the actors involved had performed the work on stage previously, adding to the stellar overall performance. A particular highlight is Olivier''s magnificent',
  1936,
  96,
  null,
  '{Drama,Comedy,Romance,Elisabeth Bergner}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/AsYouLikeIt1936',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/publicdomain/mark/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/AsYouLikeIt1936',
  '{"identifier":"AsYouLikeIt1936","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/publicdomain/mark/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/AsYouLikeIt1936',
  'https://archive.org/download/AsYouLikeIt1936/AsYouLikeIt_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'royal-wedding-1951-royal-wedding',
  'Royal Wedding',
  'Brother and sister dancing duo Tom and Ellen Bowen (Fred Astaire and Jane Powell) travel to merry old England. There, against the backdrop of the impending wedding of royals, they go about the usual comedic pursuit of love. This film is probably most memorable for Astaire''s dream sequence that has him dancing on the ceiling. The source is not of the best quality, with analog artifacts and blownout',
  1951,
  91,
  null,
  '{Musical,Comedy,Dance}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/royal_wedding',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/royal_wedding',
  '{"identifier":"royal_wedding","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/royal_wedding',
  'https://archive.org/download/royal_wedding/royal_wedding_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'scarlet-street-1945-scarletstreet',
  'Scarlet Street',
  'German director Fritz Lang is best known for the highly influential films from relatively early in his career, especially Metropolis (1927) and M (1931). But he also had a brief Hollywood heyday during the mid 1940s, when he made some of his best films. Scarlet Street has been claimed by film noir. This attribution is understandable. The lighting is dark, with heavy use of shadows. The characters ',
  1945,
  103,
  null,
  '{Film-Noir,Drama,Black Comedy,Fritz Lang}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/ScarletStreet',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/ScarletStreet',
  '{"identifier":"ScarletStreet","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/ScarletStreet',
  'https://archive.org/download/ScarletStreet/Scarlet_Street_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'sex-madness-1938-sex-madness-acm',
  'Sex Madness',
  'From the makers of Reefer Madness comes Sex Madness. A film demonstrating that sex can be just as detrimental as marijuana.',
  1938,
  51,
  null,
  '{Sex,Exploitation}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/sex_madness_ACM',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/sex_madness_ACM',
  '{"identifier":"sex_madness_ACM","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/sex_madness_ACM',
  'https://archive.org/download/sex_madness_ACM/sex_madness_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'the-flying-deuces-1939-theflyingdeuces',
  'The Flying Deuces',
  'This was the first comedy that Laurel and Hardy starred in without producer Hal Roach, although they had previously been "guest stars" in four MGM movies. After they finished making "The Flying Deuces," they returned to Hal Roach Studios to make films. In order to make this movie, producer Boris Morros bought the rights to the 1931 French film "Les deux legionnaires," which had a similar plot. "Th',
  1939,
  69,
  null,
  '{Comedy,Laurel And Hardy}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/TheFlyingDeuces',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/TheFlyingDeuces',
  '{"identifier":"TheFlyingDeuces","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/TheFlyingDeuces',
  'https://archive.org/download/TheFlyingDeuces/The_Flying_Deuces_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'meet-john-doe-1941-meet-john-doe',
  'Meet John Doe',
  'You can find more information regarding this film on <a href="http://imdb.com/title/tt0033891/" rel="nofollow">its IMDb page</a>.',
  1941,
  122,
  null,
  '{Comedy,Pdmovies}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/meet_john_doe',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/meet_john_doe',
  '{"identifier":"meet_john_doe","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/meet_john_doe',
  'https://archive.org/download/meet_john_doe/meet_john_doe_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'charlie-chaplins-the-pawnshop-1916-cc-1916-10-02-thepawnshop',
  'Charlie Chaplin''s " The Pawnshop"',
  'Charlie Chaplin''s 56th Film Released Oct 02 1916. The Pawnshop was Charlie Chaplin''s sixth film for Mutual Film Company. Chaplin played the role of assistant to the pawnshop owner. Henry Bergman played the owner and Edna Purviance the owner''s daughter. Albert Austin played an alarm clock owner who watches Charlie in dismay as he checks out the clock. This was one of Chaplin''s more popular Mutual F',
  1916,
  null,
  null,
  '{Charlie Chaplin,Silents}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/CC_1916_10_02_ThePawnshop',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/CC_1916_10_02_ThePawnshop',
  '{"identifier":"CC_1916_10_02_ThePawnshop","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/CC_1916_10_02_ThePawnshop',
  'https://archive.org/download/CC_1916_10_02_ThePawnshop/CC_1916_10_02_ThePawnshop_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'little-princess-the-1939-little-princess',
  'Little Princess, The',
  'You can find more information regarding this film on <a href="http://imdb.com/title/tt0031580/" rel="ugc nofollow">its IMDb page</a>. This film contributed courtesy of <a href="http://www.sabucat.com" rel="ugc nofollow">SabuCat Productions</a>.',
  1939,
  92,
  null,
  '{Classic}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/little_princess',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/little_princess',
  '{"identifier":"little_princess","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/little_princess',
  'https://archive.org/download/little_princess/little_princess_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'impact-1949-impact',
  'Impact',
  '"Wealthy businessman survives attempt by wife to have him killed, makes it look like she succeeded and starts a new life in small town as auto mechanic. Variation on idea elevated to noir importance by The Killers (1946), where victim of femme fatale tries to abandon the city and his past identity." - noir expert Spencer Selby',
  1949,
  109,
  null,
  '{Pdmovies}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/impact',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/impact',
  '{"identifier":"impact","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/impact',
  'https://archive.org/download/impact/impact_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'cyrano-de-bergerac-1950-cyrano-debergerac',
  'Cyrano De Bergerac',
  'From:<a href="http://www.imdb.com/title/tt0042367/" rel="ugc nofollow">IMDb</a>: France, 1640: Cyrano, the charismatic swordsman-poet with the absurd nose, hopelessly loves the beauteous Roxane; she, in turn, confesses to Cyrano her love for the handsome but tongue-tied Christian. The chivalrous Cyrano sets up with Christian an innocent deception, with tragic results. Much cut from the play, but d',
  1950,
  112,
  'eng',
  '{Drama}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/Cyrano_DeBergerac',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/Cyrano_DeBergerac',
  '{"identifier":"Cyrano_DeBergerac","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/Cyrano_DeBergerac',
  'https://archive.org/download/Cyrano_DeBergerac/Cyrano_De_Bergerac_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'cosmos-war-of-the-planets-1977-cosmos-war-of-the-planets',
  'Cosmos: War of the Planets',
  'A spaceship intercepts a mysterious message and then crashes on the planet the message is being sent from. There they uncover a force that threatens to take over the Earth. There is an AVI of the film <a href="http://www.archive.org/details/CosmosWarofthePlanets" rel="ugc nofollow">here</a>. You can find out more about this movie on its <a href="" rel="ugc nofollow">IMDB page</a>.',
  1977,
  89,
  'eng',
  '{Sci-fi,Robots,Technology,Dubbed}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/Cosmos_War_of_the_Planets',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/Cosmos_War_of_the_Planets',
  '{"identifier":"Cosmos_War_of_the_Planets","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/Cosmos_War_of_the_Planets',
  'https://archive.org/download/Cosmos_War_of_the_Planets/Cosmos_War_of_the_Planets_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'horror-express-1973-horror-express',
  'Horror Express',
  '<table width="95%" align="center" cellpadding="12"><tr bgcolor="#DDDDDD"><td> <font size="+1">In 1906, on a train racing through Siberia, Christopher Lee and Peter Cushing are engulfed in nightmare when a frozen missing link comes to life. </font> </td> </tr></table> You can load the mpeg2 file into DVDAuthorGUI (a free program) and, with the push of a button, quickly create the structure of a DVD',
  1973,
  87,
  null,
  '{Horror,Peter Cushing,Christopher Lee,Telly Savalas}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/Horror_Express',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/Horror_Express',
  '{"identifier":"Horror_Express","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/Horror_Express',
  'https://archive.org/download/Horror_Express/Horror_Express_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'tarzan-and-the-green-goddess-1938-tarzan-and-the-green-goddess',
  'Tarzan and the Green Goddess',
  'You can find more information regarding this film on <a href="http://www.imdb.com/title/tt0030832/" rel="ugc nofollow">its IMDb page</a>.',
  1938,
  null,
  null,
  '{Adventure}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/tarzan_and_the_green_goddess',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/tarzan_and_the_green_goddess',
  '{"identifier":"tarzan_and_the_green_goddess","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/tarzan_and_the_green_goddess',
  'https://archive.org/download/tarzan_and_the_green_goddess/tarzan_and_the_green_goddess_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'carnival-of-souls-1962-carnivalofsouls',
  'Carnival of Souls',
  'Atmospheric 60s B-horror film with a cult following. Mary Henry is enjoying the day by riding around with two friends but everything goes wrong when challenged to a drag race and their car gets forced off of a bridge. The car sinks into the murky depths, and all three women are assumed drowned. Some time later Mary emerges unscathed from the river. She tries to start a new life by becoming a churc',
  1962,
  82,
  null,
  '{Thriller,Horror}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/CarnivalofSouls',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/CarnivalofSouls',
  '{"identifier":"CarnivalofSouls","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/CarnivalofSouls',
  'https://archive.org/download/CarnivalofSouls/CarnivalOfSouls_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'the-gun-and-the-pulpit-1974-cco-thegunandthepulpit',
  'The Gun and the Pulpit',
  'An on the run gunfighter, wanted for a crime he didn''t commit, stumbles upon the body of a preacher who''s been killed. In an attempt to hide from his pursuers, he takes on the dead preacher''s identity and proceeds to make quite an impression on an entire town that is being bullied by an arrogant, controlling man and his cronies. Read more about this movie on this <a href="http://imdb.com/title/tt0',
  1974,
  74,
  null,
  '{Western,Comedy,Marjoe gortner,Pamela martin}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/cco_thegunandthepulpit',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/cco_thegunandthepulpit',
  '{"identifier":"cco_thegunandthepulpit","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/cco_thegunandthepulpit',
  'https://archive.org/download/cco_thegunandthepulpit/ccoPublicDomainThe_Gun_and_the_Pulpit_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'quicksand-1950-quicksand-clear',
  'Quicksand',
  '<table width="95%" align="center" cellpadding="12"><tbody><tr bgcolor="#DDDDDD"><td><font size="+.2">An engrossing suspense film with Mickey Rooney, Peter Lorre, and Jeanne Cagney. Needing money for a date, Rooney borrows $20 from the cash register, starting a chain of events that includes car theft, burglary, and possibly murder. (Yes, that is Jack Elam in the bar scene.) Read more at the <a href',
  1950,
  78,
  null,
  '{Suspense,Noir,Crime,Mickey Rooney}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/Quicksand_clear',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/publicdomain/mark/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/Quicksand_clear',
  '{"identifier":"Quicksand_clear","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/publicdomain/mark/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/Quicksand_clear',
  'https://archive.org/download/Quicksand_clear/Quicksand.mp4',
  'mp4',
  'h.264'
),
(
  'shame-1962-shame',
  'Shame',
  'Shame also known as "I Hate Your Guts" "The Intruder" is a 1962 film directed by Roger Corman starring William Shatner as a racist mystery man sent to stir trouble in a southern town that is about to integrate its high school. Roger Corman claims this is the only film of the over 300 he''s produced to lose money.',
  1962,
  84,
  null,
  '{Drama,William Shatner}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/shame_',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/shame_',
  '{"identifier":"shame_","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/shame_',
  'https://archive.org/download/shame_/Shame_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'sherlock-holmes-and-the-secret-weapon-1943-secret-weapon',
  'Sherlock Holmes and the Secret Weapon',
  'Based on the Sir Authur Conan Doyle story "The Dancing Men", Sherlock Holmes and Dr. Watson are placed in WWII europe to help protect a scientist and his invention from the Nazis. Basil Rathbone .... Sherlock Holmes Nigel Bruce .... Dr. John H. Watson Lionel Atwill .... Professor Moriarty Kaaren Verne .... Charlotte Eberli William Post Jr. .... Dr. Franz Tobel Dennis Hoey .... Inspector Lestrade H',
  1943,
  67,
  null,
  '{Mystery,Crime,Sherlock Holmes}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/secret_weapon',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/secret_weapon',
  '{"identifier":"secret_weapon","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/secret_weapon',
  'https://archive.org/download/secret_weapon/secret_weapon_ipod_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'bronenosets-potyomkin-battleship-potemkin-1925-battleshippotemkin',
  'Bronenosets Potyomkin (Battleship Potemkin)',
  'Considered one of the most important films in the history of silent pictures, as well as possibly Eisenstein''s greatest work, Battleship Potemkin brought Eisenstein''s theories of cinema art to the world in a powerful showcase; his emphasis on montage, his stress of intellectual contact, and his treatment of the mass instead of the individual as the protagonist. The film tells the story of the muti',
  1925,
  73,
  null,
  '{Silent,Drama,History,War}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/BattleshipPotemkin',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/BattleshipPotemkin',
  '{"identifier":"BattleshipPotemkin","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/BattleshipPotemkin',
  'https://archive.org/download/BattleshipPotemkin/Battleship_Potemkin_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'teaserama-1955-teaserama',
  'Teaserama',
  'This, uh, documentary is a compilation of performances by strippers and comedians featuring Bettie Page and Tempest Storm. <a href="http://www.imdb.com/title/tt0048700/" rel="ugc nofollow">IMDb Page</a>',
  1955,
  67,
  'eng',
  '{Stripper,Comedy,Burlesque,Variety}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/Teaserama',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/Teaserama',
  '{"identifier":"Teaserama","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/Teaserama',
  'https://archive.org/download/Teaserama/Teaserama_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'double-feature-hell-2-the-grindhouse-experience-doublefeaturehell2thegrindhouseexperience',
  'DOUBLE FEATURE HELL 2 (the grindhouse experience).',
  'ADULT CONTENT ADVISORY: this grindhouse double feature simulation contains nudity and other content some viewers might find objectionable.<br /> <br /> Your night in the sleazy side of town begins with three trailers and a Betty Page short, followed by the first feature, "Diary of a Nudist." An intermission featurette is next, "Naked Fury," followed by the second feature, "Revenge of the Virgins."',
  null,
  144,
  null,
  '{2am Theater,Double feature,Grindhouse,Exploiatation}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/DoubleFeatureHell2theGrindhouseExperience',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/publicdomain/mark/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/DoubleFeatureHell2theGrindhouseExperience',
  '{"identifier":"DoubleFeatureHell2theGrindhouseExperience","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/publicdomain/mark/1.0/',
  'Source: Internet Archive',
  'https://archive.org/details/DoubleFeatureHell2theGrindhouseExperience',
  'https://archive.org/download/DoubleFeatureHell2theGrindhouseExperience/DoubleFeatureHell2theGrindhouseExperience.mp4',
  'mp4',
  'MPEG4'
),
(
  'great-expectations-1946-greatexpectations1946',
  'Great Expectations (1946)',
  'The classic story of Pip the British orphan. Great Expectations (1946) Fall''s Under The Transitional Aspects Of UK Law. http://www.archive.org/post/285670/are-these-public-domain <a href="http://mystic-nights.com/videos/" rel="ugc nofollow">Mystic Nights Videos</a>',
  null,
  113,
  null,
  '{John Mills,Tony Wager,Alec Guinness,Valerie Hobson}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/GreatExpectations1946',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/GreatExpectations1946',
  '{"identifier":"GreatExpectations1946","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/GreatExpectations1946',
  'https://archive.org/download/GreatExpectations1946/GreatExpectations1946_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'charlie-chaplins-the-count-1916-cc-1916-09-04-thecount',
  'Charlie Chaplin''s "The Count"',
  'Charlie Chaplin''s 55th Film released Sept. 04 1916. The Count was Charlie Chaplin''s fifth film for Mutual Films. Co-starring Eric Campbell and Edna Purviance, it is a story about Charlie and his boss finding an invitation to a party from a real Count. Each try to play the role as the Count instead to catch the rich heiress played by Edna <a href="http://www.imdb.com/title/tt0006548/" rel="ugc nofo',
  1916,
  null,
  null,
  '{Charlie Chaplin,Silents}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/CC_1916_09_04_TheCount',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/CC_1916_09_04_TheCount',
  '{"identifier":"CC_1916_09_04_TheCount","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/CC_1916_09_04_TheCount',
  'https://archive.org/download/CC_1916_09_04_TheCount/CC_1916_09_04_TheCount_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'the-ghoul-1933-theghoul',
  'The Ghoul',
  'The Ghoul is a 1933 British Horror film starring Boris Karloff, Cedric Hardwicke, Ernest Thesiger and Ralph Richardson, whose debut film this was. The plot centres around a Professor (Karloff) who is to be buried with an Egyptian jewel in order to attain eternal life. When the jewel is stolen by his servant, the professor rises from the dead to reclaim it. The film, based on the play and novel by ',
  1933,
  68,
  'eng',
  '{Horror,Egypt,Mummy,Boris Karloff}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/TheGhoul',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/TheGhoul',
  '{"identifier":"TheGhoul","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/TheGhoul',
  'https://archive.org/download/TheGhoul/TheGhoul_1933_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'the-iron-mask-1929-iron-mask',
  'The Iron Mask',
  'A swashbuckling Alexandre Dumas adventure featuring Douglas Fairbanks. You can find more information regarding this film on <a href="http://www.imdb.com/title/tt0020030/" rel="ugc nofollow">its IMDb page</a>.',
  1929,
  null,
  null,
  '{Adventure,Romance}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/iron_mask',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/iron_mask',
  '{"identifier":"iron_mask","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/iron_mask',
  'https://archive.org/download/iron_mask/iron_mask_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'the-three-stooges-color-craziness-color-craziness-the-three-stooges-colorcrazinessthethreestooges',
  'The Three Stooges - "Color Craziness" "Color Craziness" - The Three Stooges',
  '"The New Three Stooges" was produced in 1965. It featured the animated adventures of Moe, Larry, & Curly Joe. The cartoons were introduced by live-action inserts with the real Stooges. These inserts were some of the only Stooges material ever filmed in color, and they also feature long-time Stooge collaberator Emil Sitka. "The Three Stooges - Color Craziness" is an hour feature comprised of these ',
  null,
  3290,
  null,
  '{Three stooges comedy}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/ColorCrazinessTheThreeStooges',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/ColorCrazinessTheThreeStooges',
  '{"identifier":"ColorCrazinessTheThreeStooges","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/ColorCrazinessTheThreeStooges',
  'https://archive.org/download/ColorCrazinessTheThreeStooges/threestoogescolorcraziness_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'the-amazing-adventure-1936-amazing-adventure',
  'The Amazing Adventure',
  'Cary Grant plays Earnest Bliss a rich socialite who makes a bet with his doctor that he can make a living for one year using none of his current wealth.',
  1936,
  61,
  null,
  '{Romance,Comedy,Drama}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/amazing_adventure',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/amazing_adventure',
  '{"identifier":"amazing_adventure","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/amazing_adventure',
  'https://archive.org/download/amazing_adventure/amazing_adventuarchive_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
),
(
  'the-birth-of-a-nation-1915-dw-griffith-birth-of-a-nation',
  'The Birth of a Nation',
  'In its time, "The Birth of a Nation" was a masterpiece. Its racist undertones and revisionism are quite disturbing, but it is still worth watching for its historical influence. IMDb entry: http://imdb.com/title/tt0004972/',
  1915,
  null,
  null,
  '{D.W. Griffith,The Clansman,Silent,Pdmovies}'::text[],
  '{}'::text[],
  'https://archive.org/services/img/dw_griffith_birth_of_a_nation',
  null,
  'public_domain',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/dw_griffith_birth_of_a_nation',
  '{"identifier":"dw_griffith_birth_of_a_nation","rights":"","provider":"internet_archive"}'::jsonb,
  'Internet Archive',
  'archive',
  'Public Domain',
  'http://creativecommons.org/licenses/publicdomain/',
  'Source: Internet Archive',
  'https://archive.org/details/dw_griffith_birth_of_a_nation',
  'https://archive.org/download/dw_griffith_birth_of_a_nation/birth_of_a_nation_512kb.mp4',
  'mp4',
  '512Kb MPEG4'
);

insert into public.legal_catalog_items (
  slug,
  title,
  description,
  release_year,
  runtime_minutes,
  language_code,
  genres,
  countries,
  poster_url,
  backdrop_url,
  source_type,
  license_type,
  license_url,
  attribution_text,
  external_url,
  metadata_json,
  is_active
)
select
  slug,
  title,
  description,
  release_year,
  runtime_minutes,
  language_code,
  genres,
  countries,
  poster_url,
  backdrop_url,
  source_type,
  license_type,
  license_url,
  attribution_text,
  external_url,
  metadata_json,
  true
from tmp_legal_seed
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  release_year = excluded.release_year,
  runtime_minutes = excluded.runtime_minutes,
  language_code = excluded.language_code,
  genres = excluded.genres,
  countries = excluded.countries,
  poster_url = excluded.poster_url,
  source_type = excluded.source_type,
  license_type = excluded.license_type,
  license_url = excluded.license_url,
  attribution_text = excluded.attribution_text,
  external_url = excluded.external_url,
  metadata_json = excluded.metadata_json,
  is_active = true,
  updated_at = now();

insert into public.legal_sources (
  item_id,
  provider_name,
  provider_type,
  license_type,
  license_url,
  attribution_text,
  territories,
  external_watch_url,
  metadata_json,
  is_active
)
select
  i.id,
  s.provider_name,
  s.provider_type,
  s.source_license_type,
  s.source_license_url,
  s.source_attribution_text,
  '{}'::text[],
  s.source_external_url,
  jsonb_build_object('seed', 'archive_org'),
  true
from tmp_legal_seed s
join public.legal_catalog_items i on i.slug = s.slug;

insert into public.legal_stream_variants (
  item_id,
  source_id,
  stream_url,
  format,
  quality_label,
  region_allowlist,
  requires_auth,
  is_embeddable,
  is_active,
  metadata_json
)
select
  i.id,
  src.id,
  s.stream_url,
  s.stream_format,
  s.quality_label,
  '{}'::text[],
  false,
  true,
  true,
  jsonb_build_object('seed', 'archive_org')
from tmp_legal_seed s
join public.legal_catalog_items i on i.slug = s.slug
left join lateral (
  select ls.id
  from public.legal_sources ls
  where ls.item_id = i.id
  order by ls.id desc
  limit 1
) src on true
where s.stream_url is not null
  and s.stream_url <> '';
